### ISSUE TITLE
Исключить поле «дата закрытия заявки» в формах у Инженера  

### ISSUE THREAD

**Issue by faralost** [python9students/ESDP-Project-Service-Desk#101]
Наблюдаемый сценарий:
сейчас он не дает отредактировать и выдает такую ошибку при нажатии на кнопку «сохранить»:
https://ibb.co/mFdPsvd

Ожидаемый сценарий:
Инженер редактирует заявку, нажимает «сохранить» - заявка сохраняется отредактированной

**Comment by Yusupov-Aslan** [comment]
Исправил bug, работает по ожидаемому сценарию!
